/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Unlock": "解锁",
    "True Sacrifice": "真正的牺牲",
    "Prestiges": "声望",
    "Prestigious": "声名显赫",
    "Qualities of Life": "生活质量",
    "Refund on prestige": "声望返还",
    "Reset": "重置",
    "Reward": "奖励",
    "Reward: Achievement 3-6 is boosted based on equation clicks [": "奖励：成就 3-6 基于方程式点击而提升 [",
    "Reward: Automation is": "奖励：自动化",
    "Reward: Challenge completions boost PP gain [": "奖励：挑战完成提升声望点增益[",
    "Reward: Challenge goals are lower based on IP [": "奖励:基于 增量点 的挑战目标更低[",
    "Reward: Challenge rewards are boosted based on tree upgrades bought [": "奖励：根据购买的树升级来提升挑战奖励[",
    "Reward: Clicking is boosted based on total clicks [": "奖励：点击根据总点击次数增加 [",
    "Reward: P's cost scales": "奖励：P 的成本缩放",
    "Reward: Sacrifices boost PP gain [": "奖励：牺牲提升声望点增益[",
    "Reward: Start with": "奖励：开始时有",
    "Reward: The E multiplier is": "奖励：E 乘数是",
    "Reward: The first automation is": "奖励：第一个自动化是",
    "Reward: You gain": "奖励：你获得",
    "S+1: Sacrifice IP": "S+1：牺牲增量点",
    "S+2: Sacrifice PP": "S+2：牺牲声望点",
    "Sacrifice": "牺牲",
    "Sacrifice all your IP and PP content for a boost": "牺牲您所有的 增量点 和 声望点 内容以获得提升",
    "Sacrifice is cheaper": "牺牲更便宜",
    "Sacrifice for the first time": "第1次牺牲",
    "Sacrifice PP for the first time": "第1次牺牲声望点",
    "Sacrifice PP two times": "牺牲2次声望点",
    "Sacrifice seven times": "牺牲7次",
    "Sacrifice two times": "牺牲2次",
    "Sacrifice without buying any variables": "牺牲不买任何变量",
    "Sacrifice without losing anything": "牺牲而不失去任何东西",
    "Sacrifice your IP and variables for a boost": "牺牲你的 增量点 和变量来提升",
    "Sacrifice your PP": "牺牲你的声望点",
    "Subtraction": "减法",
    "Save and Load": "保存/加载",
    "Scaling": "缩放",
    "scalings": "缩放",
    "Scaling upgrades are better based on total PP": "基于总 声望点 的缩放升级更好",
    "Scientific": "科学",
    "Shift click an automation to toggle all automation in that tab": "Shift 单击一个自动化以切换该选项卡中的所有自动化",
    "Show logarithmic progress bars": "显示对数进度条",
    "Show offline production": "显示离线生产",
    "Slow Down": "减速",
    "slower": "更慢",
    "stronger": "更强",
    "substantially faster": "明显更快",
    "Tetration": "四分法",
    "The answer": "答案",
    "The first automation is faster based on equation clicks": "第一个自动化基于方程式点击更快",
    "The first milestone applies to prestige": "第一个里程碑适用于声望",
    "Timber": "木材",
    "times": "次",
    "times this prestige": "本次声望时间",
    "Toggle smart auto prestige": "切换智能自动声望",
    "Version": "版本",
    "Variable P": "变量 P",
    "When you prestige, auto prestige will be set to prestige at the same PP you just prestiged at": "当你声望时，自动声望将设置为你刚刚声望的同一个声望点的声望",
    "You are gaining": "你正在获得",
    "You can hold enter after clicking a button to auto click it 10x per second": "您可以在单击按钮后按住 回车 键以每秒 10 次自动单击它",
    "You gained": "你获得了",
    "ou have been playing for": "你已经玩了",
    "You have clicked the equation": "您点击了等式",
    "You have completed": "你完成了",
    "You have found": "你找到了",
    "You have gained a total of": "你总共获得了",
    "You have prestiged": "你声望了",
    "You have sacrificed": "你牺牲了",
    "You prestiged": "你声望了",
    "You were away for": "你离开了",
    "Your fastest prestige lasted": "你最快的声望持续了",
    "Your highest IP is": "你的最高增量点是",
    "Your last prestige was": "你最后的声望是",
    "Your PP is multiplying IP gain by": "您的 声望点 将 增量点 增益乘以",
    "Need": "需要",
    "Next in": "下一个在",
    "Normal": "正常",
    "Options": "选项",
    "Error": "错误",
    "Easy prestige": "轻松声望",
    "Easy sacrifice": "轻松牺牲",
    "Eggs": "蛋",
    "egg": "蛋",
    "Milestones": "里程碑",
    "Prestige Points": "声望点",
    "Prestige": "声望",
    "Prestige at": "声望在",
    "Prestige enough times to unlock useful features": "获得足够的声望来解锁有用的功能",
    "Prestige for the first time": "第1次声望",
    "Challenge": "挑战",
    "Challenges": "挑战",
    "Change tabs on challenge entry": "更改挑战条目的选项卡",
    "Click a few times": "点击几次",
    "Click the equation 3,333 times": "单击方程 3,333 次",
    "Climbing High": "攀登高峰",
    "Close": "关闭",
    "Exponential": "指数",
    "Exponential age": "指数时代",
    "faster": "更快",
    "Full automation": "全自动化",
    "Fully automate prestiges": "全自动声望",
    "Goal": "目标",
    "Get 1,000 P without any P1": "无需任何 P1 即可获得 1,000 P",
    "Haha it's harder now": "哈哈现在更难了",
    "I think it was worth it": "我认为这是值得的",
    "Import 42": "导入 42",
    "IP on all resets": "所有重置的 增量点",
    "IP is boosted based on IP": "增量点基于增量点提升",
    "It's not better": "这不是更好",
    "Loading... Can take up to a minute": "正在加载...最多可能需要一分钟",
    "Keep all variables unlocked on all resets": "在所有重置时保持所有变量解锁",
    "Logarithm": "对数",
    "more effective": "更加有效",
    "more PP": "更多 PP",
    "The prestige tree is disabled": "声望树被禁用",
    "The second milestone applies to prestige": "第二个里程碑适用于声望",
    "Tree": "树",
    "This was worth it": "这是值得的",
    "This is too easy": "这太容易了",
    "Weakling": "弱者",
    "What's New?": "有什么新东西？",
    "You have been playing for": "你已经玩了",
    "Was it worth it?": "它值得吗？",
    "/Click": "/点击",
    "/sec": "/秒",
    "/sec) Prestige at": "/秒) 声望在",
    "achievement": "成就",
    "Addition": "加法",
    "are": "",
    "ago": "前",
    "AP per second": "转生点 每秒",
    "Ascension": "转生",
    "Ascension Points": "转生点",
    "Auto retry challenges": "自动重试挑战",
    "Stonks": "重炮猛轰",
    "Stonks 2.0": "重炮猛轰 2.0",
    "StonksThat was quite a mistake": "重炮猛轰那是个大错",
    "Auto stonks": "自动重炮猛轰",
    "Automate automation": "自动自动化",
    "Automate Automation (": "自动自动化 (",
    "Automate Prestige (": "自动声望 (",
    "Automate Sacrifice (": "自动牺牲 (",
    "Automate Scaling (": "自动缩放 (",
    "Automate IP Gain (": "自动 增量点 增益 (",
    "Automate E Gain (": "自动 E 增益 (",
    "Automate M Gain (": "自动 M 增益 (",
    "Automate P Gain (": "自动 P 增益 (",
    "Automate T Gain (": "自动 T 增益 (",
    "Automation": "自动化",
    "Automation boosts apply to auto sacrifice and prestige": "自动化提升适用于自动牺牲和声望",
    "Automation clicks the equation": "自动化点击方程式",
    "Automation speed is faster based on total PP": "基于总 声望点 的自动化速度更快",
    "Automation speed is slower based on completed achievements": "根据完成的成就自动化速度较慢",
    "based on IP": "基于 增量点",
    "Begin automation": "开始自动化",
    "Blind": "盲文",
    "boosted based on IP": "基于增量点的提升",
    "Boosts: IP⇒": "提升: 增量点⇒",
    "Buy the second T variable": "购买第二个 T 变量",
    "Buy your first scaling E upgrade": "购买您的第一个缩放 E 升级",
    "Buying any variables resets all lower variables and sacrifice is 5x weaker": "购买任何变量都会重置所有较低的变量，并且牺牲会弱 5 倍",
    "Buying automation levels now buys as many as possible": "现在购买尽可能多的自动化级别",
    "Buying scaling levels now buys as many as possible": "购买缩放级别现在购买尽可能多",
    "Can you even call this a sacrifice anymore?": "你还能称这为牺牲吗？",
    "capped at": "上限为",
    "Complete challenges multiple times for better rewards": "多次完成挑战以获得更好的奖励",
    "Complete prestige challenge 1 for the first time": "首次完成声望挑战 1",
    "Confirmations": "确认",
    "Congrats?": "恭喜？",
    "Cost": "成本",
    "Current ip infinity is": "当前 增量点无限 是",
    "Current pp infinity is": "当前 声望点无限 是",
    "Currently in challenge": "目前在挑战",
    "Decimals on exponents": "指数的小数",
    "Free money": "免费的钱",
    "Game Saved": "游戏已保存",
    "Increase the cap for prestige tree upgrade 1-3": "增加声望树升级1-3的上限",
    "Increment": "增量",
    "Increment Points": "增量点",
    "Increment's cost scales": "增量的成本缩放",
    "Infinity": "无限",
    "Infinite": "无限",
    "IP per second": "增量点 每秒",
    "Locked": "未解锁",
    "Multiplication": "乘法",
    "Achievements are": "成就",
    "Achievement 2-4 is stronger based on IP": "成就2-4基于增量点更强",
    "Achievement 3-2 is tetrated 3 times": "成就 3-2 被四化 3 次",
    "Achievement 3-1 is boosted based on highest IP": "成就3-1基于最高增量点提升",
    "Achievement 3-3 is boosted based on achievements": "成就3-3根据成就提升",
    "Tree upgrade 1-1 gets an exponent based on total PP": "树升级 1-1 获得基于总 声望点 的指数",
    "Tree upgrade 1-2 affects the E multiplier with reduced effect": "树升级 1-2 影响 E 乘数，但效果降低",
    "Tree upgrade 3-3 is stronger based on completed challenges": "树升级 3-3 基于完成的挑战更强",
    "Remove the cap for tree upgrade 5-4": "移除树升级的上限 5-4",
    "Automate IP": "自动增量点",
    "Automate P Variables": "自动 P 变量",
    "IP sacrifice no longer resets your automation and scaling levels": "增量点 牺牲不再重置您的自动化和缩放级别",
    "IP sacrifice no longer resets your IP": "增量点 牺牲不再重置您的 增量点",
    "IP sacrifice no longer resets your variables": "增量点 牺牲不再重置您的变量",
    "IP sacrifice no longer turns off automation": "增量点 牺牲不再关闭自动化",
    "IP sacrifice, scalings and challenge 3 are disabled": "增量点 牺牲、缩放和挑战 3 被禁用",
    "Is it easy already?": "已经很容易了吗？",
    "IP sacrifices boost": "增量点牺牲提升",
    "Is not affected by 3-3": "不受3-3影响",
    "Is this too worth it?": "这也太值得了吧？",
    "Multipliers P & M are better based on total PP": "基于总 声望点 的乘数 P & M 更好",
    "Multipliers per variable: P⇒": "每个变量的乘数：P⇒",
    "Multiplying IP gain by": "将 增量点 增益乘以",
    "Notations": "符号",
    "Note: Do not spoil these to others, they are secret": "注意：不要把这些泄露给别人，它们是秘密的",
    "Only affects 1st layer's automation": "只影响第一层的自动化",
    "P Variables are cheaper based on their base": "P 变量基于它们的基数更便宜",
    "P variables are disabled, but you start with each purchased once": "P 变量被禁用，但你开始每个购买一次",
    "P variables gain an exponent based on their base": "P 变量基于它们的基数获得一个指数",
    "P: Prestige": "P: 声望",
    "PP boost to IP is": "声望点 对 增量点 的提升是",
    "PP per second": "声望点 每秒",
    "PP sacrifice no longer resets challenges": "声望点牺牲不再重置挑战",
    "Prestige goal scales slower based on scaling levels": "声望目标会根据缩放级别变慢",
    "Prestige Tree and Milestones": "声望树和里程碑",
    "Prestige tree upgrades": "声望树升级",
    "Prestige tree upgrades boost automation speed": "声望树升级提高自动化速度",
    "Prestige while sacrificing at most 10 times": "最多牺牲10次声望",
    "Prestige without buying any variables": "声望不买任何变量",
    "Prestige without sacrificing": "声望不牺牲",
    "IP go brrrrr": "增量点 到 brrrrr",
    "That was quite a mistake": "那是一个很大的错误",
    "Yep, it's there": "是的，它在那里",
    "Are you sure you want to sacrifice?": "你确定要牺牲？",
    "Cancel": "取消",
    "PP Milestone": "声望点 里程碑",
    "Variable M, P Multiplier": "变量 M, P 乘数",
    "Variable T,": "变量 T,",
    "OK": "确定",
    "Nothing": "无",
    "Variable M": "变量 M",
    "IP": "增量点",
    "PP": "声望点",
    "AP": "转生点",
    "M Multiplier": "M 乘数",
    "Automate M Variables": "自动 M 变量",
    "Variable E": "变量 E",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Buy your first (.+) variable$/, '购买您的第1个 $1 变量'],
    [/^Scaling (.+) Variables$/, '缩放 $1 变量'],
    [/^Buy prestige upgrade (.+)$/, '购买声望升级 $1'],
    [/^Loaded Version (.+)$/, '已加载版本 $1'],
    [/^Reduce (.+) Costs \($/, '降低 $1 成本（'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+) Hours, ([\d\.]+) Minutes, ([\d\.]+) Seconds$/, '$1 小时, $2分钟, $3 秒'],
	[/^([\d\.]+) Minutes, ([\d\.]+) Seconds$/, '$1 分钟, $2 秒'],
	[/^([\d\.]+) Minute, ([\d\.]+) Seconds$/, '$1 分钟, $2 秒'],
	[/^([\d\.]+) Year$/, '$1 年'],
	[/^([\d\.]+) Minute,$/, '$1 分钟,'],
	[/^([\d\.]+) Seconds$/, '$1 秒'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);